variables:
    DOCKER_IMAGE_NAME_BASE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

stages:
    - package
    
web:
    image: docker:latest
    stage: package
    script:
        - docker login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
        - docker build --pull --no-cache --tag $DOCKER_IMAGE_NAME_BASE-$CI_JOB_NAME --file Dockerfile.d/$CI_JOB_NAME .
        - docker push $DOCKER_IMAGE_NAME_BASE-$CI_JOB_NAME

cli:
    image: docker:latest
    stage: package
    script:
        - docker login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
        - docker build --pull --no-cache --tag $DOCKER_IMAGE_NAME_BASE-$CI_JOB_NAME --file Dockerfile.d/$CI_JOB_NAME .
        - docker push $DOCKER_IMAGE_NAME_BASE-$CI_JOB_NAME
